using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HMS.Application.Features.Bookings.Commands.Create
{
    public class CreateBookingCommand : IRequest<Result<int>>
    {
        //public string BookingNumber { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public string? Notes { get; set; }
        public string Currency { get; set; }
        public bool IsInvoiceAutoGenerated { get; set; }


        public int PatientId { get; set; }
        public int RoomId { get; set; }
        public int WardId { get; set; }
    }
}
